apiVersion: apps/v1
kind: Deployment
metadata:
  name: argon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argon
  template:
    metadata:
      labels:
        app: argon
    spec:
      containers:
        - name: argon-container
          image: balaakashreddyy/argon-design-cicd:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argon-service
spec:
  type: NodePort
  selector:
    app: argon
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
