apiVersion: apps/v1
kind: Deployment
metadata:
  name: argon-green
  labels:
    app: argon-web
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argon-web
      version: green
  template:
    metadata:
      labels:
        app: argon-web
        version: green
    spec:
      containers:
        - name: argon-web
          image: __IMAGE_PLACEHOLDER__
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
