apiVersion: apps/v1
kind: Deployment
metadata:
  name: argon-green
  labels:
    app: argon-web
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argon-web
      version: green
  template:
    metadata:
      labels:
        app: argon-web
        version: green
    spec:
      imagePullSecrets:
        - name: regcred   # remove if not needed
      containers:
        - name: argon-web
          image: ${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
