apiVersion: apps/v1
kind: Deployment
metadata:
  name: argon-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argon-web
      version: blue
  template:
    metadata:
      labels:
        app: argon-web
        version: blue
    spec:
      containers:
      - name: argon-web
        image: balaakashreddyy/argon-web:blue
        ports:
        - containerPort: 80
