apiVersion: v1
kind: Service
metadata:
  name: argon-bluegreen-service
spec:
  type: NodePort
  selector:
    app: argon-web
    version: blue
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31050
